# Generated by Django 6.0.6 on 2026-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(max_length=255, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('type_message', models.CharField(choices=[('text', 'Texte'), ('audio', 'Vocal'), ('other', 'Autre')], max_length=10)),
                ('contenu_texte', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('answered', 'Répondu'), ('escalated', 'Escaladé')], default='pending', max_length=20)),
                ('reponse_envoyee', models.TextField(blank=True)),
                ('recu_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
