# Generated by Django 6.0.6 on 2026-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecu',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('answered', 'Répondu'), ('escalated', 'Escaladé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
    ]
