# Generated by Django 6.0.6 on 2026-07-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_alter_messagerecu_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecu',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('en_traitement', 'En traitement'), ('repondu_auto', 'Répondu automatiquement'), ('repondu_manuel', 'Répondu manuellement'), ('escalade', 'Escaladé'), ('echec', 'Échec technique')], default='nouveau', max_length=20),
        ),
    ]
