# Generated by Django 6.0.6 on 2026-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_alter_messagerecu_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecu',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios_recus/'),
        ),
    ]
