# Generated by Django 5.2.15 on 2026-06-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('message', models.TextField(verbose_name='Message à envoyer')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi programmée")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('programmee', 'Programmée'), ('en_cours', "En cours d'envoi"), ('terminee', 'Terminée'), ('echec', 'Échec')], default='brouillon', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numéro WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('lu', 'Lu par le client'), ('echec', 'Échec')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('message_id_whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Message WhatsApp')),
                ('erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='campagnes.campagne', verbose_name='Campagne')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='campagnes.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Envoi de message',
                'verbose_name_plural': 'Envois de messages',
                'ordering': ['-date_envoi'],
                'unique_together': {('campagne', 'client')},
            },
        ),
    ]
