# Generated by Django 5.2.15 on 2026-06-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du template (Meta)')),
                ('categorie', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utilitaire'), ('AUTHENTICATION', 'Authentification')], max_length=20, verbose_name='Catégorie')),
                ('langue', models.CharField(default='en_US', max_length=10, verbose_name='Code langue (ex: en_US, fr, ar)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20, verbose_name='Statut Meta')),
                ('contenu_body', models.TextField(help_text='Ex: Bonjour {{1}}, votre commande {{2}} est prête.', verbose_name='Contenu du body')),
                ('nombre_variables', models.PositiveIntegerField(default=0, verbose_name='Nombre de variables ({{1}}, {{2}}...)')),
                ('date_creation_meta', models.DateTimeField(blank=True, null=True, verbose_name='Date de création chez Meta')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation Meta")),
                ('description', models.TextField(blank=True, verbose_name='Description / Usage')),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
                'ordering': ['-date_approbation', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='variables_template',
            field=models.JSONField(blank=True, default=list, help_text='["Ikram", "#CMD-1234", "250"]', verbose_name='Valeurs des variables'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes', to='campagnes.templatewhatsapp', verbose_name='Template WhatsApp utilisé'),
        ),
    ]
