# Generated by Django 5.2.15 on 2026-06-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0002_templatewhatsapp_campagne_variables_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='message',
        ),
        migrations.AlterField(
            model_name='campagne',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('programmee', 'Programmée'), ('en_cours', "En cours d'envoi"), ('terminee', 'Terminée'), ('partiel', 'Terminée avec erreurs'), ('echec', 'Échec')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
    ]
