# Generated by Django 6.0.6 on 2026-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0003_remove_campagne_message_alter_campagne_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewhatsapp',
            name='contenu_footer',
            field=models.CharField(blank=True, help_text='Ex: Répondez STOP pour vous désabonner.', max_length=60, verbose_name='Contenu du footer (optionnel)'),
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='contenu_header',
            field=models.CharField(blank=True, help_text='Texte affiché en gras au-dessus du message. Max 60 caractères.', max_length=60, verbose_name='Contenu du header (optionnel)'),
        ),
    ]
