# Generated by Django 6.0.6 on 2026-06-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0004_templatewhatsapp_contenu_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewhatsapp',
            name='exemples_variables_body',
            field=models.JSONField(blank=True, default=list, help_text='Ex: ["Ali", "CMD-123"]', verbose_name='Exemples des variables body'),
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='fichier_header_exemple',
            field=models.FileField(blank=True, help_text='Image, vidéo ou document exemple pour les headers média.', null=True, upload_to='whatsapp/templates/headers/', verbose_name='Fichier exemple du header'),
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='type_header',
            field=models.CharField(choices=[('NONE', 'Aucun'), ('TEXT', 'Texte'), ('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], default='NONE', max_length=20, verbose_name='Type de header'),
        ),
        migrations.AlterField(
            model_name='templatewhatsapp',
            name='contenu_footer',
            field=models.CharField(blank=True, help_text='Texte optionnel affiché sous le body. Max 60 caractères.', max_length=60, verbose_name='Contenu du footer'),
        ),
        migrations.AlterField(
            model_name='templatewhatsapp',
            name='contenu_header',
            field=models.CharField(blank=True, help_text='Utilisé seulement si le type de header est TEXT. Max 60 caractères.', max_length=60, verbose_name='Texte du header'),
        ),
        migrations.AlterField(
            model_name='templatewhatsapp',
            name='langue',
            field=models.CharField(default='en_US', max_length=10, verbose_name='Code langue'),
        ),
        migrations.AlterField(
            model_name='templatewhatsapp',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du template Meta'),
        ),
        migrations.AlterField(
            model_name='templatewhatsapp',
            name='nombre_variables',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de variables dans le body'),
        ),
        migrations.CreateModel(
            name='BoutonTemplateWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre')),
                ('type_bouton', models.CharField(choices=[('QUICK_REPLY', 'Réponse rapide'), ('URL', 'Lien'), ('PHONE_NUMBER', 'Numéro de téléphone')], max_length=20, verbose_name='Type de bouton')),
                ('texte', models.CharField(max_length=25, verbose_name='Texte du bouton')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('numero_telephone', models.CharField(blank=True, max_length=30, verbose_name='Numéro de téléphone')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutons', to='campagnes.templatewhatsapp', verbose_name='Template WhatsApp')),
            ],
            options={
                'verbose_name': 'Bouton de template WhatsApp',
                'verbose_name_plural': 'Boutons de template WhatsApp',
                'ordering': ['template', 'ordre'],
                'constraints': [models.UniqueConstraint(fields=('template', 'ordre'), name='unique_ordre_bouton_template_whatsapp')],
            },
        ),
    ]
