# Generated by Django 6.0.6 on 2026-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0005_templatewhatsapp_exemples_variables_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='entreprise',
            field=models.CharField(blank=True, max_length=100, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('vip', 'VIP')], default='prospect', max_length=20, verbose_name='Segment'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
    ]
