# Generated by Django 6.0.6 on 2026-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0006_client_entreprise_client_segment_client_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='mapping_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Ex: {"1": "client.nom", "2": "client.ville", "3": "fixe:Promo Été"}', verbose_name='Mapping des variables'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='variables_template',
            field=models.JSONField(blank=True, default=list, help_text='["Ikram", "#CMD-1234", "250"]', verbose_name='Valeurs des variables (statique)'),
        ),
    ]
