# Generated by Django 6.0.6 on 2026-07-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0007_campagne_mapping_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewhatsapp',
            name='add_security_recommendation',
            field=models.BooleanField(default=True, verbose_name='Ajouter la recommandation de sécurité'),
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='code_expiration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name="Durée d'expiration du code"),
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='otp_button_text',
            field=models.CharField(default='Copier le code', max_length=25),
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='otp_type',
            field=models.CharField(choices=[('COPY_CODE', 'Copy Code'), ('ONE_TAP', 'One Tap'), ('ZERO_TAP', 'Zero Tap')], default='COPY_CODE', max_length=20),
        ),
    ]
