# Generated by Django 6.0.6 on 2026-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0008_templatewhatsapp_add_security_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatewhatsapp',
            name='contenu_body',
            field=models.TextField(blank=True, default='', help_text='Ex: Bonjour {{1}}, votre commande {{2}} est prête.', verbose_name='Contenu du body'),
        ),
    ]
