# Generated by Django 6.0.6 on 2026-07-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0009_alter_templatewhatsapp_contenu_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='template_id_meta',
            field=models.CharField(blank=True, help_text='ID retourné par Meta à la création (obligatoire pour éditer le template ensuite).', max_length=50, null=True, verbose_name='ID Meta du template'),
        ),
    ]
