# Generated by Django 6.0.6 on 2026-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0010_campagne_template_id_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='template_id_meta',
        ),
        migrations.AddField(
            model_name='templatewhatsapp',
            name='template_id_meta',
            field=models.CharField(blank=True, help_text='ID retourné par Meta à la création (obligatoire pour éditer le template ensuite).', max_length=50, null=True, verbose_name='ID Meta du template'),
        ),
    ]
